Repository udemy-final-team2/Book-Hub-Project, pull requests merged in 2023-02, with the labels that each got.

#29 Feature/#6 o auth2 refactoring
  .gitignore
  src/main/java/com/example/BookHub/BookHubApplication.java
  src/main/java/com/example/BookHub/Config/OAuth2/CustomOAuth2UserService.java
  src/main/java/com/example/BookHub/Config/OAuth2/OAuthAttributes.java
  src/main/java/com/example/BookHub/Config/OAuth2/SecurityConfig.java
  src/main/java/com/example/BookHub/HomeController.java
  src/main/java/com/example/BookHub/ServletInitializer.java
  src/main/java/com/example/BookHub/User/UserController.java
  src/main/java/com/example/BookHub/User/UserDTO.java
  src/main/java/com/example/BookHub/User/UserRepository.java
  src/main/java/com/example/BookHub/User/UserService.java
  src/main/java/com/example/BookHub/Util/SessionConst.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/mybatis/mapper/user-mapper.xml
  src/main/resources/static/css/docs.css
  src/main/webapp/WEB-INF/views/signin.jsp
Labels: enhancement

#36 Feature/#31 docs page
  src/main/java/com/example/BookHub/User/UserDTO.java
  src/main/resources/static/css/docs.css
  src/main/resources/static/css/index.css
  src/main/webapp/WEB-INF/views/docs.jsp
Labels: enhancement

#37 #31-모달창 추가, css 수정
  src/main/resources/static/css/docs.css
  src/main/webapp/WEB-INF/views/docs.jsp
Labels: enhancement

#38 #31-문서 검색기능 추가
  src/main/resources/static/css/docs.css
  src/main/webapp/WEB-INF/views/docs.jsp
Labels: enhancement

#39 #31-문서, 폴더 관련 로직 1차 커밋
  .gitignore
  build.gradle
  src/main/java/com/example/BookHub/Docs/DocsController.java
  src/main/java/com/example/BookHub/Docs/DocsDTO.java
  src/main/java/com/example/BookHub/Docs/DocsRepository.java
  src/main/java/com/example/BookHub/Docs/DocsService.java
  src/main/java/com/example/BookHub/Folder/FolderController.java
  src/main/java/com/example/BookHub/Folder/FolderDTO.java
  src/main/java/com/example/BookHub/Folder/FolderRepository.java
  src/main/java/com/example/BookHub/Folder/FolderService.java
  src/main/resources/application.yml
  src/main/resources/mybatis/mapper/docs-mapper.xml
  src/main/resources/mybatis/mapper/folder-mapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/signin.jsp
Labels: enhancement

#46 Feature/#31 docs list page
  src/main/resources/static/css/docs.css
  src/main/resources/static/css/login.css
  src/main/resources/static/js/docs.js
  src/main/webapp/WEB-INF/views/docs.jsp
  src/main/webapp/WEB-INF/views/signin.jsp
  src/main/webapp/WEB-INF/views/signup.jsp
Labels: enhancement

#67 Feature/#66 복사, 번역기 링크 버튼 구현 및 CSS 적용
  src/main/resources/static/css/writeform.css
  src/main/resources/static/img/copy.png
  src/main/resources/static/img/save.png
  src/main/webapp/WEB-INF/views/writeform.jsp
Labels: enhancement

#69 Featuer/#41-admin
  src/main/java/com/example/BookHub/User/UserController.java
  src/main/java/com/example/BookHub/User/UserDTO.java
  src/main/java/com/example/BookHub/User/UserRepository.java
  src/main/java/com/example/BookHub/User/UserService.java
  src/main/resources/mybatis/mapper/user-mapper.xml
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/mypage.jsp
  src/main/webapp/WEB-INF/views/usermanage.jsp
Labels: enhancement

#72 #56- 관리자 내문의 댓글작성
  src/main/java/com/example/BookHub/Post/CommentDTO.java
  src/main/java/com/example/BookHub/Post/PostController.java
  src/main/java/com/example/BookHub/Post/PostDTO.java
  src/main/java/com/example/BookHub/Post/PostRepository.java
  src/main/java/com/example/BookHub/Post/PostService.java
  src/main/resources/mybatis/mapper/post-mapper.xml
  src/main/webapp/WEB-INF/views/insertpost.jsp
  src/main/webapp/WEB-INF/views/post.jsp
  src/main/webapp/WEB-INF/views/postlist.jsp
Labels: enhancement

#73 #64-문서 관련 로직 1차 수정
  src/main/java/com/example/BookHub/Docs/DocsController.java
  src/main/java/com/example/BookHub/Docs/DocsRepository.java
  src/main/java/com/example/BookHub/Docs/DocsService.java
  src/main/java/com/example/BookHub/Folder/FolderController.java
  src/main/java/com/example/BookHub/User/UserController.java
  src/main/resources/application.yml
  src/main/resources/mybatis/mapper/docs-mapper.xml
  src/main/resources/static/css/docs.css
  src/main/webapp/WEB-INF/views/docs.jsp
  src/main/webapp/WEB-INF/views/writeform.jsp
Labels: enhancement

#77 Feature/#65 spring security+jwt
  .gitignore
  build.gradle
  src/main/java/com/example/BookHub/Docs/DocsController.java
  src/main/java/com/example/BookHub/Post/PostController.java
  src/main/java/com/example/BookHub/Security/ApplicationConfig.java
  src/main/java/com/example/BookHub/Security/Auth/AuthenticationController.java
  src/main/java/com/example/BookHub/Security/Auth/AuthenticationRequest.java
  src/main/java/com/example/BookHub/Security/Auth/AuthenticationResponse.java
  src/main/java/com/example/BookHub/Security/Auth/AuthenticationService.java
  src/main/java/com/example/BookHub/Security/Auth/RegisterRequest.java
  src/main/java/com/example/BookHub/Security/JwtAuthenticationFilter.java
  src/main/java/com/example/BookHub/Security/JwtService.java
  src/main/java/com/example/BookHub/Security/LogoutService.java
  src/main/java/com/example/BookHub/Security/OAuth2/CustomOAuth2User.java
  src/main/java/com/example/BookHub/Security/OAuth2/CustomOAuth2UserService.java
  src/main/java/com/example/BookHub/Security/OAuth2/OAuth2LoginFailureHandler.java
  src/main/java/com/example/BookHub/Security/OAuth2/OAuth2LoginSuccessHandler.java
  src/main/java/com/example/BookHub/Security/OAuth2/OAuthAttributes.java
  src/main/java/com/example/BookHub/Security/OAuth2/SocialType.java
  src/main/java/com/example/BookHub/Security/OAuth2/UserInfo/GoogleOAuth2UserInfo.java
  src/main/java/com/example/BookHub/Security/OAuth2/UserInfo/KaKaoOAuth2UserInfo.java
  src/main/java/com/example/BookHub/Security/OAuth2/UserInfo/NaverOAuth2UserInfo.java
  src/main/java/com/example/BookHub/Security/OAuth2/UserInfo/OAuth2UserInfo.java
  src/main/java/com/example/BookHub/Security/SecurityConfiguration.java
  src/main/java/com/example/BookHub/Security/Token/TokenDTO.java
  src/main/java/com/example/BookHub/Security/Token/TokenRepository.java
  src/main/java/com/example/BookHub/Security/Token/TokenType.java
  src/main/java/com/example/BookHub/User/Role.java
  src/main/java/com/example/BookHub/User/UserController.java
  src/main/java/com/example/BookHub/User/UserDTO.java
  src/main/java/com/example/BookHub/User/UserRepository.java
  src/main/java/com/example/BookHub/User/UserService.java
  src/main/resources/mybatis/mapper/token-mapper.xml
  src/main/resources/mybatis/mapper/user-mapper.xml
  src/main/resources/mybatis/mybatis-config.xml
  src/main/webapp/WEB-INF/views/signup.jsp
  src/test/java/com/example/BookHub/Security/JwtServiceTest.java
Labels: enhancement, EPIC

#79 Feature/#78 security rollback
  src/main/java/com/example/BookHub/Config/OAuth2/CustomOAuth2UserService.java
  src/main/java/com/example/BookHub/Config/OAuth2/OAuthAttributes.java
  src/main/java/com/example/BookHub/Config/OAuth2/SecurityConfig.java
  src/main/java/com/example/BookHub/Security/Auth/AuthenticationService.java
  src/main/java/com/example/BookHub/Security/OAuth2/OAuth2LoginSuccessHandler.java
  src/main/java/com/example/BookHub/Security/OAuth2/OAuthAttributes.java
  src/main/java/com/example/BookHub/Security/SecurityConfiguration.java
  src/main/java/com/example/BookHub/User/UserController.java
  src/main/java/com/example/BookHub/User/UserDTO.java
  src/main/java/com/example/BookHub/User/UserRepository.java
  src/main/java/com/example/BookHub/User/UserService.java
  src/main/resources/mybatis/mapper/user-mapper.xml
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/mypage.jsp
Labels: duplicate

#86 Feture#84 usermanage
  src/main/java/com/example/BookHub/Post/PostController.java
  src/main/java/com/example/BookHub/Post/PostRepository.java
  src/main/java/com/example/BookHub/Post/PostService.java
  src/main/java/com/example/BookHub/User/UserController.java
  src/main/java/com/example/BookHub/User/UserRepository.java
  src/main/java/com/example/BookHub/User/UserService.java
  src/main/resources/mybatis/mapper/post-mapper.xml
  src/main/resources/mybatis/mapper/user-mapper.xml
  src/main/webapp/WEB-INF/views/insertpost.jsp
  src/main/webapp/WEB-INF/views/post.jsp
  src/main/webapp/WEB-INF/views/postlist.jsp
  src/main/webapp/WEB-INF/views/usermanage.jsp
Labels: enhancement
